services:
  - type: web
    name: fmsportalgy-api
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: fmsportalgy-db
          property: connectionString
databases:
  - name: fmsportalgy-db
    plan: free
